name: CI setup for PostgreSQL
description: Configure your workflow with easy PostgreSQL setup
author: RillSvai
branding:
  icon: database
  color: blue
inputs:
  version:
    description: Version of PostgreSQL engine
    required: false
    default: latest
  user:
    description: Username for PostgreSQL server
    required: false
    default: postgres
  password:
    description: Password for your user
    required: false
    default: password
  db_name:
    description: Name for your database that will be created
    required: false
    default: postgres
runs:
  using: docker
  image: Dockerfile
